apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rflnmrh8e-python 
  janus-idp.io/tekton: rflnmrh8e-python
  backstage.io/kubernetes-id: rflnmrh8e-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rflnmrh8e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml