apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rflnmrh8e-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:68b86047a38ab33eff461971c7939c3aa18c27c6@sha256:f41a0056bbe7aa98052f1dacbf6f5bb825ab2da060215942b97aa585c560141a
          name: container-image
